// ERRORS
export const SET_ERROR = 'SET_ERROR';

// LOADING
export const SET_LOADING = 'SET_LOADING';

// MODAL
export const UPDATE_MODAL = 'UPDATE_MODAL';

// LOGIN
export const LOGOUT = 'LOGOUT';
export const RECEIVE_USER_SESSION = 'RECEIVE_USER_SESSION';
export const RECEIVE_AVAILABLE_GROUPS = 'RECEIVE_AVAILABLE_GROUPS';

// RUN
export const RECEIVE_RUN = 'RECEIVE_RUN';
export const RECEIVE_RUN_VARIABLES = 'RECEIVE_RUN_VARIABLES';
export const RECEIVE_WORLD = 'RECEIVE_WORLD';
export const UPDATE_RUN_METADATA = 'UPDATE_RUN_METADATA';

// INPUT
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_INPUTS = 'UPDATE_INPUTS';

// SETTINGS
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';

// FACILITATOR
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST';
export const RECEIVE_WORLD_LIST = 'RECEIVE_WORLD_LIST';
export const RECEIVE_PERSONAS = 'RECEIVE_PERSONAS';
